###admin login
POST http://localhost:2167/user-api/users/login
Content-Type: application/json

{
    "email":"admin123@gmail.com",
    "password":"admin1234"
}
###Read users
GET http://localhost:2167/admin-api/users

###Blocking the user
PATCH http://localhost:2167/admin-api/users
Content-Type: application/json

{
    "userId":"69f8a526edb8f75bef0fd9c1",
    "isUserActive":false
}

###admin logout
GET http://localhost:2167/user-api/users/logout