###new post
POST http://localhost:2167/post-api/posts
Content-Type: application/json

{
    "author":"69f8a526edb8f75bef0fd9c1",
    "content":"What A Wonderful Day!"
}

###read
GET http://localhost:2167/post-api/posts

###Post update
PUT http://localhost:2167/post-api/posts
Content-Type: application/json

{
    "postId":"69f8baf7dd2eb74896af5f99",
    "content":"What A Beautiful Night!"
}

###delete post
PATCH http://localhost:2167/post-api/posts
Content-Type: application/json

{
    "postId":"69f8baf7dd2eb74896af5f99",
    "isPostActive":false
}

###like/unlike post
PATCH http://localhost:2167/post-api/posts/69f8baf7dd2eb74896af5f99/like

###comments on post
PUT http://localhost:2167/post-api/posts/comments
Content-Type: application/json

{
    "postId":"69f8baf7dd2eb74896af5f99",
    "comment":"Surely it is. 😍"
}
###Reading posts with commented user info
GET http://localhost:2167/post-api/posts/69f8baf7dd2eb74896af5f99

###Delete comment
DELETE http://localhost:2167/post-api/posts/69f8baf7dd2eb74896af5f99/comments/69f9ac6f9edc1c54b1b1b3c5