###user registration
POST http://localhost:2167/user-api/users
Content-Type: application/json

{
    "firstName":"Lexus",
    "lastName":"Hamilton",
    "userName":"lexus_la123",
    "email":"lexushamilton123@gmail.com",
    "password":"lexushamilton"
}

###user login
POST http://localhost:2167/user-api/users/login
Content-Type: application/json

{
    "idCreds":"lexus_la123",
    "password":"lexushamilton"
}

###user logout
GET http://localhost:2167/user-api/users/logout

###getting posts
GET http://localhost:2167/user-api/posts

###Search users
GET http://localhost:2167/user-api/users/search?query=nexu